def hesaplamalarmenü():
    print("╔══════════════════════════════════╗")
    print("║          HESAPLAMALAR            ║")
    print("╠══════════════════════════════════╣")
    print("║   1-Toplama                      ║")
    print("║   2-Çıkarma                      ║")
    print("║   3-Çarpma                       ║")
    print("║   4-Bölme                        ║")
    print("║   5-Üst Alma                     ║")
    print("║   6-Çarpım Tablosu               ║")
    print("║   7-Diködörtgen Alanı            ║")
    print("║   8-Dikdörtgen Çevresi           ║")
    print("║   9-Anamenü                      ║")
    print("║  10-Çıkış                        ║")
    print("║                                  ║")
    print("║         Seçiminiz nedir?         ║")
    print("╚══════════════════════════════════╝")
    seçim=input()
    